import { imageLoader, IImage, metaData, Enums } from '@cornerstonejs/core';

// WHY: We need a custom image loader because we are fetching raw uncompressed binary buffers
// generated by our Python sidecar and served over Tauri's custom `oct-asset://` protocol.
// This is much faster and uses less memory than passing base64 JSON over IPC.

interface Manifest {
  width: number;
  height: number;
  bitDepth: number;
  pixelSpacing: number[];
  [key: string]: any;
}

// Global manifest registry so the loader knows the dimensions of the images it's fetching
let currentManifest: Manifest | null = null;

export function setLoaderManifest(manifest: Manifest) {
  currentManifest = manifest;
}

function loadImage(imageId: string): { promise: Promise<IImage>; cancelFn: () => void | undefined } {
  const promise = new Promise<IImage>(async (resolve, reject) => {
    try {
      if (!currentManifest) {
        throw new Error("Manifest not set before loading images.");
      }

      console.debug(`Loading image: ${imageId}`);
      const startTime = performance.now();

      // Convert octAsset://imageId to oct-asset://localhost/imageId
      // wait, the imageId passed to cornerstone might be 'octAsset:///slice_000.raw'
      // We will parse it to fetch from tauri's asset protocol.
      const url = imageId.replace('octAsset://', 'http://oct-asset.localhost/'); // Tauri v2 custom protocol on WebKit usually uses http://<scheme>.localhost/
      // Actually, Tauri v2 custom protocols are `http://<scheme>.localhost/` on macOS/Windows and `https://<scheme>.localhost/` or custom.
      // Let's use `convertFileSrc` from @tauri-apps/api/core if it's a file, but here we registered a custom protocol.
      // For Tauri custom protocol registered as `oct-asset`, the URL should be `http://oct-asset.localhost/` or `asset://localhost/`.
      // Let's just use `fetch('http://oct-asset.localhost/' + path)` or just relative fetch if possible.
      // Better yet, we can use `fetch('http://oct-asset.localhost' + path)` directly.
      const fetchUrl = `http://oct-asset.localhost` + imageId.replace('octAsset://', '');
      
      const response = await fetch(fetchUrl);
      
      if (!response.ok) {
        throw new Error(`Failed to fetch image: ${response.statusText}`);
      }
      
      const arrayBuffer = await response.arrayBuffer();
      
      const { width, height, bitDepth, pixelSpacing } = currentManifest;
      const pixelData = bitDepth === 16 ? new Uint16Array(arrayBuffer) : new Uint8Array(arrayBuffer);

      console.debug(`Image loaded in ${Math.round(performance.now() - startTime)}ms. Size: ${pixelData.byteLength} bytes.`);

      const image: IImage = {
        imageId,
        minPixelValue: 0,
        maxPixelValue: bitDepth === 16 ? 65535 : 255,
        slope: 1,
        intercept: 0,
        windowCenter: bitDepth === 16 ? 32768 : 128,
        windowWidth: bitDepth === 16 ? 65535 : 255,
        getPixelData: () => pixelData,
        getCanvas: () => {
          throw new Error('getCanvas is not implemented');
        },
        rows: height,
        columns: width,
        height,
        width,
        color: false,
        rgba: false,
        columnPixelSpacing: pixelSpacing[0],
        rowPixelSpacing: pixelSpacing[1],
        invert: false,
        sizeInBytes: pixelData.byteLength,
        numComps: 1,
        isPreScaled: false,
      };

      resolve(image);
    } catch (error) {
      console.error(error);
      reject(error);
    }
  });

  return {
    promise,
    cancelFn: () => {},
  };
}

export function registerOCTImageLoader() {
  imageLoader.registerImageLoader('octAsset', loadImage);
}
